name: Java CI with Gradle (Updated)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Gradle Wrapperを最新に更新（Gradle 8.10）
    - name: Update Gradle Wrapper
      run: ./gradlew wrapper --gradle-version 8.10 --distribution-type bin

    # Gradle セットアップ（キャッシュ有効化）
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # ビルド実行
    - name: Build with Gradle Wrapper
      run: ./gradlew build --warning-mode all

    # ビルド成果物アップロード
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
